#version: '3.7'
#
#services:
#  abfrage-supporter:
#    build:
#      context: .
#    ports:
#      - "80:80"


version: '3.7'

services:
  api:
    container_name: supporter-selbstauskunft-terminal
    image: git.kulturkosmos.de/pascal/abfrage-api-supporter:latest  # Angepasst: korrekte Image-URL mit Repository-Pfad und Tag
    restart: on-failure
    env_file:
      - .env
    ports:
      - "80:80"  # Port-Mapping: Host-Port 80 auf Container-Port 80
    depends_on:
      - psql

  psql:
    container_name: supporter-selbstauskunft-psql
    image: postgres:14.1-alpine  # Beispiel: Postgres-Image, angepasst nach Bedarf
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"  # Beispiel: Port-Mapping für Postgres
    volumes:
      - ./psql:/var/lib/postgresql/data  # Beispiel: Volume für Persistenz der Datenbank